version: '2'

services:
  corewebapi:
    image: corewebapi:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
